"""change_roles_to_admin_manager_staff

Revision ID: 4552d45c6604
Revises: 29a9e40808c1
Create Date: 2026-03-14 22:41:23.415281

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4552d45c6604"
down_revision: Union[str, None] = "29a9e40808c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=6),
        type_=sa.Enum("admin", "manager", "staff", name="user_role", native_enum=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.Enum(
            "admin", "manager", "staff", name="user_role", native_enum=False
        ),
        type_=sa.VARCHAR(length=6),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
